version: '3.1'
services:
  redis:
    image: redis:6
    restart: always
    container_name: ipv6-address-acquisition-redis
    volumes:
      - ./volumes/redis/data:/data
    command: redis-server --requirepass server123456
    ports:
      - "6001:6379"