"""Initial migration

Revision ID: a8e04527de77
Revises: 
Create Date: 2024-01-20 17:08:35.641496

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a8e04527de77'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'network',
        sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column('ip_addr', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'),
                  autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint('id', name='network_pkey')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('network')
    # ### end Alembic commands ###
