"""empty message

Revision ID: 680f6d15d878
Revises: 
Create Date: 2024-02-19 15:27:28.681320

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '680f6d15d878'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ip_addr',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('addr', sa.VARCHAR(length=39), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='ip_addr_pkey')
    )
    op.create_table('ip_ddns',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ip_addr_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('domain_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('rr', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('ttl', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='ip_ddns_pkey')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ip_ddns')
    op.drop_table('ip_addr')
    # ### end Alembic commands ###
